### ISSUE TITLE
Invalid session token. Please try to reload the page because the operation has not been performed

### ISSUE THREAD

**Issue by AlexL777** [PHPBoost/PHPBoost#97]
Hello Developers,

I use PHPBoost 5.0 and can not log in 10 hours since the session token does not work. My website is at https://phpboost.wpzweinull.ch.

How can I solve the problem or can you perhaps help me?

Thanks in advance.

**Comment by babsolune** [comment]
Hi
Did you choose to log in with a login name at the install process or not ?
If not, you have to log in with your email address, and edit your profile to choose the "login name" connection

If the problem is different, please give us the real error message you get

**Comment by janus57** [comment]
Hello,

you should the V5.0 of PHPBoost, not the git master nor alpha version.
You can find the stable version here : https://www.phpboost.com/download/44-phpboost-5-0/361-phpboost-5-0/

Cordially, janus57

**Comment by AlexL777** [comment]
Hello you two,

I use the last PHPBoost version from the GitHub releases. Now I have made a simple update for testing and can not enter the login.

How can I disable the maintenance mode in the FTP account, so I can log in?

I want to check again if there is still session token problems.

Thanks in advance.

**Comment by janus57** [comment]
Hello,

you cannot mix the V5.0 and V5.1 since their are not compatible witout using migration script which are under dev.

So i recommand you to use the V5.0 to production website with the link to phpboost.com that i gave you.

If you want to test the Alpha version you need to start with installing the Alpha alone on not start from to V5.0 to a V5.1A2
But Alpha version are not recommanded to be used in production.

Cordially, janus57

**Comment by AlexL777** [comment]
Ok, I understood that well. But now my website is in maintenance mode and I can not log in anyway.

How can I log in if the maintenance mode is still active?

**Comment by janus57** [comment]
Hello,

you need to restore the V5.0 because now you have a mix of 2 différentes version that cause your problem.

And the only way to have you website back is to restore a full V5.0 without a mix of V5.1

Notice : i recommand to use the download on phpboost website since the archive are better optimized than the git.

Cordially, janus57

**Comment by AlexL777** [comment]
Since I created my PHPboost website yesterday without content, I have now done a complete reinstallation. I took the version you suggested to me here.

But already complicated when the website is in the maintenance mode and I can not log in :smile:

But well, if I should have more problems, I create here still issues. In addition, I will have a lot of questions about PHPboost. Unfortunately, the documentation is in French. Let's see how I can translate this quickly.

**Comment by janus57** [comment]
Hello,

you should login when the website is in maintenance mode (with the email address or the nickname if you have used one at setup).
But in your case you have made a bad mix with different versions so you may have broken the authentification.

For the documentation unfortunately we don't have enough people in the team to write it in French **and** translate it in English.

If your problem is solved, I invite you to lock the issue.

Cordially, janus57

**Comment by AlexL777** [comment]
Ok, thanks for the hints.

Now I have PHPBoost 5.0 from the official website of you guys. I test again after logging in again.

Yes, you can now close this issue and with further questions I know where I can find the support.

**Comment by janus57** [comment]
Hello,

also don't hesitate to register and post on the community forum at https://www.phpboost.com/forum/

Notice : but we don't have English sections because they were not used in the past years :'(

Cordially, janus57

**Comment by AlexL777** [comment]
Thanks, I will ask my questions in French. That should not be the problem, I think.
